//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopifyTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopifyTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        /// {
        ///  &quot;order_id&quot;: 1,
        ///  &quot;shop_id&quot;: 53,
        ///  &quot;user_id&quot;: 746,
        ///  &quot;order_amount&quot;: 224,
        ///  &quot;total_items&quot;: 2,
        ///  &quot;payment_method&quot;: &quot;cash&quot;,
        ///  &quot;created_at&quot;: &quot;2017-03-13 12:36:56&quot;
        /// },
        /// {
        ///  &quot;order_id&quot;: 2,
        ///  &quot;shop_id&quot;: 92,
        ///  &quot;user_id&quot;: 925,
        ///  &quot;order_amount&quot;: 90,
        ///  &quot;total_items&quot;: 1,
        ///  &quot;payment_method&quot;: &quot;cash&quot;,
        ///  &quot;created_at&quot;: &quot;2017-03-03 17:38:52&quot;
        /// },
        /// {
        ///  &quot;order_id&quot;: 3,
        ///  &quot;shop_id&quot;: 44,
        ///  &quot;user_id&quot;: 861,
        ///  &quot;order_amount&quot;: 144,
        ///  &quot;total_items&quot;: 1,
        ///  &quot;payment_method&quot;: &quot;cash&quot;,
        ///  &quot;created_at&quot;: &quot;2017-03-14 4:23:56&quot;
        /// },
        /// {
        ///  &quot;or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
    }
}
